### ISSUE TITLE
Pixel-Wise Reliability Measure

### ISSUE THREAD

**Issue by forrestfwilliams** [nasa-jpl/autoRIFT#47]
Hello, thank for creating this wonderful program. I was wondering if AutoRIFT includes, or if there are any plans to include a pixel-wise reliability measure for the displacements results.

In particular, something similar to the correlation coefficent mentioned in issue #43 or the signal to noise ratio band provided by Cosi-Corr would be great.

I understand that this may not be a quick add-in, but it would really help others interpret the results produced by AutoRIFT!

**Comment by alex-s-gardner** [comment]
@forrestfwilliams thanks for the suggestion, it is completely logical. At this time we have no plans to add a pixel-wise reliability metric as we haven't found that they can improve upon the Normalized Displacement Coherence filter (NDC: see SI of https://tc.copernicus.org/articles/12/521/2018/) currently implemented with in autoRIFT. In addition to the time of implementation there is an increase in compute cost without much/any benefit. We played around with many metrics early on (see https://www.sciencedirect.com/science/article/pii/S003442571530211X) but didn't find them all that reliable for distinguishing good/bad data for various reasons
