### ISSUE TITLE
Error encountered when running testGeogrid_ISCE.py

### ISSUE THREAD

**Issue by bjmarfito** [nasa-jpl/autoRIFT#48]
When I ran the testGeogrid_ISCE.py on two Sentinel-1 SLC images, I encountered an error message 
```
libc++abi: terminating with uncaught exception of type std::length_error: vector
zsh: abort
```

I used the command `testGeogrid_ISCE.py -m ../20170701_20170707_des_S1_neworb_nasadem/fine_coreg -s ../20170701_20170707_des_S1_neworb_nasadem/secondary -d ../dem_nasa/demLat_N09_N14_Lon_E122_E127.dem.wgs84`.

**Comment by bjmarfito** [comment]
I finally resolved this issue. I used a UTM projected DEM.

**Comment by alex-s-gardner** [comment]
@bjmarfito thanks for the follow up… we’ll add a check for this when we get a chance, unless u want to generate a pull request for one?

**Comment by bjmarfito** [comment]
@alex-s-gardner, I can probably submit a PR regarding your request as early as next week.

**Comment by alex-s-gardner** [comment]
@bjmarfito that would be great!
