### ISSUE TITLE
 testGeogrid_ISCE.py   AttributeError: 'Geogrid' object has no attribute 'pOff'

### ISSUE THREAD

**Issue by guangbaoshen** [nasa-jpl/autoRIFT#55]
Hi, everyone, I use isce2.4.2 to run testGeogrid_ISCE.py, and I met the error below, is there anyone has met the error before?
thank you for your help.

theone@noone:~/AutoRIFT$ testGeogrid_ISCE.py -m ./fine_coreg/ -s ./secondary  -d ./dem/demLat_N38_N40_Lon_E116_E118.dem.wgs84
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce

Radar parameters: 
Range: 902593  2.32956
Azimuth: 79933.9  486.486
Dimensions: 25399 12261
Incidence Angle: 44.1745

Map inputs: 
EPSG: 4326
Smallest Allowable Chip Size in m: 240
Repeat Time: 1.0368e+06
XLimits: 116.089  117.426
YLimits: 38.016  39.6604
Extent in km: 0.00133725  0.00164443
DEM: ./dem/demLat_N38_N40_Lon_E116_E118.dem.wgs84

Outputs: 
Window locations: window_location.tif
Output Nodata Value: -32767

Starting processing .... 
Xlimits : 116.089  117.426
Ylimits : 38.0158  39.6606
Origin index (in DEM) of geogrid: 320   1222
Dimensions of geogrid: 4815 x 5921
Ground range pixel size: 3.34301
Azimuth pixel size: 15.6095
Traceback (most recent call last):
  File "/home/theone/isce2/install/isce/components/contrib/geo_autoRIFT/testGeogrid_ISCE.py", line 378, in <module>
    main()
  File "/home/theone/isce2/install/isce/components/contrib/geo_autoRIFT/testGeogrid_ISCE.py", line 374, in main
    runGeogrid(metadata_m, metadata_s, inps.demfile, inps.dhdxfile, inps.dhdyfile, inps.vxfile, inps.vyfile, inps.srxfile, inps.sryfile, inps.csminxfile, inps.csminyfile, inps.csmaxxfile, inps.csmaxyfile, inps.ssmfile)
  File "/home/theone/isce2/install/isce/components/contrib/geo_autoRIFT/testGeogrid_ISCE.py", line 264, in runGeogrid
    'xoff': obj.pOff,
AttributeError: 'Geogrid' object has no attribute 'pOff'

**Comment by leiyangleon** [comment]
@guangbaoshen please refer to the Geogrid instructions [here](https://github.com/leiyangleon/Geogrid/blob/master/docs/instruction.md), where it requires a northing/easting Cartesina coordinate DEM (lat/lon as directly used by ISCE is not supported). You can do gdalwarp on that file and save it as a geotiff image. Then running testGeogrid should work.
