### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getgeotransform'

### ISSUE THREAD

**Issue by gyp-1991-gq** [nasa-jpl/autoRIFT#60]
What's the reason for this? Please help me!
![image](https://user-images.githubusercontent.com/76198536/162748423-a51bc8f2-6bc0-4aca-9630-aef880919cbc.png)

**Comment by jhkennedy** [comment]
@gyp-1991-gq I'm just seeing this, do you still need help? In your error message it looks like `l1.tif` doesn't exist
