### ISSUE TITLE
Correct computation of v_error

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/autoRIFT#68]
As @alex-s-gardner pointed out, the paper and production code need to be corrected in computations of `v_error`:

https://github.com/nasa-jpl/autoRIFT/blob/e683e485b0e194a0b63def90ccbdee11ad56fb2a/netcdf_output.py#L697

It should be changed to:
`v_err = (vx_err.*abs(vx) + vy_err.*abs(vy))./v`

**Comment by alex-s-gardner** [comment]
I discussed this with Yang and the error formulation in the paper is correct. We may need to update our Mosaic code

**Comment by jhkennedy** [comment]
@alex-s-gardner so, the `netcdf_ouput.py` doesn't need to be updated, correct?

**Comment by alex-s-gardner** [comment]
@jhkennedy that is correct

**Comment by alex-s-gardner** [comment]
@mliukis when you have a chance can you confirm error calculation in mosaic code

**Comment by alex-s-gardner** [comment]
no action needed
