### ISSUE TITLE
Running autorift

### ISSUE THREAD

**Issue by SoleHeredia** [nasa-jpl/autoRIFT#76]
Hi, I have installed isce 2 on my ubuntu machine. it includes the autoRIFT module, which I want to use to calculate displacement using TSX and CSK images.  I exported the environment variables to where the autorift folders are, but when I want to run it, it does it without any error or warning but it doesn't generate any output. Can someone help me with this? I am stuck
<img width="794" alt="Capture" src="https://user-images.githubusercontent.com/39810368/222129829-b6ec1b75-9cef-4486-9aeb-9348b86e06b9.PNG">
Thank you very much!

**Comment by SoleHeredia** [comment]
Thank you @jhkennedy! Ok but I also want to use it with Sentinel 1. So, I reinstall Isce2 with conda this time, where are supposed to be testGeogrid_ISCE.py and testAutoRIFT_ISCE.py? Because they are not in the geo_autoRIFT folder, so I do not know how to use them. 
Thank you for your time and answer

**Comment by jhkennedy** [comment]
I believe this is answered -- @SoleHeredia feel free to re-open if you still need help.
