### ISSUE TITLE
Crop granules X/Y extends to valid data only

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/autoRIFT#82]
This is to incorporate the post-processing, that we had to apply to all granules on ITS_LIVE side, during granule generation. Here is the reference to the code we used:

https://github.com/nasa-jpl/its_live_production/blob/main/src/tools/crop_v2_granules.py

**Comment by jhkennedy** [comment]
@mliukis I'm working on this now. Should I *only* be looking at `crop_v2_granules.py`, or should I be looking at all three `crop_v2_*.py` scripts?

**Comment by mliukis** [comment]
crop_v2_granules.py is sufficient as I had to create other scripts to address specific to Landsat and S1 issues.
