### ISSUE TITLE
Hello teacher, I have a question. Why do the Dx and Dy values in offset. mat generated by autoRIFT are nan values, and 'InterpMask' and 'ChipSizeX' are also 0 values?

### ISSUE THREAD

**Issue by mintaizu** [nasa-jpl/autoRIFT#84]
Could the teacher please help me answer my question? This question has been bothering me for a long time! Thank you, teacher!
I am using Sentinel 1 data for processing, topApp. py for data preprocessing, and testGeogrid for data preprocessing_ ISCE.py performs geogrid as follows: testGeogrid_ ISCE.py - m/home/zhodejun/s12/fine_ Coreg - s/home/zhodejun/s12/secondary/- d/home/zhodejun/s9/output_ Dem. tif, I use testautoRIFT_ ISCE.py, as shown in testautoRIFT_ ISCE.py - m/home/zhodejun/s12/merged/reference.slc.full - s/home/zhodejun/s12/merged/secondary.slc.full
But in the final generated offset.mat file, Dx and Dy are NAN values, while 'InterpMask' and 'ChipSizeX' are 0  values ,May I ask the teacher why this is?

![屏幕截图 2023-08-20 202728](https://github.com/nasa-jpl/autoRIFT/assets/103091413/ebaf96a1-df76-4b31-9eec-9223df7f33b3)

And the two pictures of Dx and Dy are identical. Why??

![屏幕截图 2023-08-20 202802](https://github.com/nasa-jpl/autoRIFT/assets/103091413/e21933e3-22f7-4317-8f21-e5c8ada4b1f6)

**Comment by alex-s-gardner** [comment]
autoRIFT returns no data values for locations that it is unable to find a significant match between the template and the search chip. For the example that you posted, autoRIFT is not able to find any significant matches between features in the two images and therefor returns NaNs and zeros.

**Comment by alex-s-gardner** [comment]
I've added a note in the readme:

https://github.com/nasa-jpl/autoRIFT/commit/3b307c3f5c287106e1ae5c1e27b7e8fa01ab0a0b

**Comment by mintaizu** [comment]
So, teacher, do you think this is a normal situation? I did indeed experience displacement.

**Comment by alex-s-gardner** [comment]
This is indeed a normal situation.. often when matching two images there are areas with no correlatable features.

**Comment by mintaizu** [comment]
Sorry to bother you again, but can I understand that this situation is caused by issues with the sentinel data I selected?

**Comment by alex-s-gardner** [comment]
Features in repeat images change over time and it can be difficult to find matching features between two images, especially if the surface conditions have changed considerably since the first image was acquired. I would suggest you read the following to get oriented:

https://www.sciencedirect.com/science/article/pii/S003442571530211X
https://www.mdpi.com/2072-4292/13/4/749
https://essd.copernicus.org/articles/14/5111/2022/

**Comment by mintaizu** [comment]
OK , Thank you teacher！

**Comment by mintaizu** [comment]
Hello teacher, I am currently preparing to conduct research on offset tracking. I am planning to use autoRIFT to innovate on some simple aspects of autoRIFT or combine it with INSAR methods to publish a graduation thesis. May I use autoRIFT for related research innovation or to publish a paper? Will it involve copyright issues?

**Comment by alex-s-gardner** [comment]
Please refrain from posting repeated questions. All contributions, including answering questions, is done on a voluntary basis. Please be patient when waiting for a reply.

**Comment by mintaizu** [comment]
Sorry teacher, I will pay attention to my mistakes
