### ISSUE TITLE
What are the issues encountered with using autoRIFT?

### ISSUE THREAD

**Issue by mintaizu** [nasa-jpl/autoRIFT#85]
老师能帮我回答我的问题吗？这个问题困扰了我很久了！谢谢老师！
我正在使用Sentinel 1数据进行处理，topApp。py 用于数据预处理，testGeogrid 用于数据preprocessing_ ISCE.py 执行 Geogrid 如下方式执行 Geogrid： testGeogrid_ ISCE.py - m/home/zhodejun/s12/fine_ Coreg - s/home/zhodejun/s12/secondary/- d/home/zhodejun/s9/output_ Dem.tif，我使用testautoRIFT_ ISCE.py，如testautoRIFT_ ISCE.py 所示 - m/home/zhodejun/s12/merged/reference.slc.full - s/home/zhodejun/s12/merged/secondary.slc.full
但是在最终生成的 offset.mat 文件中，Dx 和 Dy 是 NAN 值，而“InterpMask”和“ChipSizeX”是 0 值，请问老师为什么会这样？

![image](https://github.com/nasa-jpl/autoRIFT/assets/103091413/ec98d7a2-60d5-4bf3-b321-eb31e536efbd)

而Dx和Dy的两张图片是相同的。为什么？？

![image](https://github.com/nasa-jpl/autoRIFT/assets/103091413/9ab04a1a-5de2-40b7-809e-0758cad448b1)

**Comment by alex-s-gardner** [comment]
This is the same issue as #84, closing
