### ISSUE TITLE
AutoRIFT citation innovation issues

### ISSUE THREAD

**Issue by mintaizu** [nasa-jpl/autoRIFT#86]
Hello teacher, I am currently preparing to conduct research on offset tracking. I am planning to use autoRIFT to innovate on some simple aspects of autoRIFT or combine it with INSAR methods to publish a graduation thesis. May I use autoRIFT for related research innovation or to publish a paper? Will it involve copyright issues?

**Comment by alex-s-gardner** [comment]
You are free use the code as you wish. We just ask that you provide proper acknowledgement by citing:

Gardner, A.S., Moholdt, G., Scambos, T., Fahnstock, M., Ligtenberg, S., Broeke, M.V.D. and Nilsson, J., 2018. [Increased West Antarctic and unchanged East Antarctic ice discharge over the last 7 years.](https://doi.org/10.5194/tc-12-521-2018) The Cryosphere, 12(2), pp.521-547.

and
 
Lei, Y., Gardner, A. and Agram, P., 2021. [Autonomous Repeat Image Feature Tracking (autoRIFT) and Its Application for Tracking Ice Displacement.](https://doi.org/10.3390/rs13040749) Remote Sensing, 13(4), p.749.

**Comment by mintaizu** [comment]
Ok, thank you, teacher
