### ISSUE TITLE
Add img_pair_info:standard_name = "image_pair_information" 

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/autoRIFT#90]
@jhkennedy I think this fell through the cracks somehow

**Comment by jhkennedy** [comment]
@mliukis this should already be there for any granule created after Nov. 23. 2022:
 * In hyp3_autorift, [here](https://github.com/ASFHyP3/hyp3-autorift/blob/develop/hyp3_autorift/vend/netcdf_output.py#L395) via ASFHyP3/hyp3-autorift#189
 * in nasa-jpl/autorift, [here](https://github.com/nasa-jpl/autoRIFT/blob/master/netcdf_output.py#L386) via #74

**Comment by mliukis** [comment]
@jhkennedy I see! One of the new S1 granules had it missing - might have been older than Nov. 23, 2023

**Comment by jhkennedy** [comment]
@mliukis I did confirm `img_pair_info:standard_name = "image_pair_information"` is being generated for all our test granules, so we're def. g2g.
